import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ALL APPS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-6 lg:m-20 bg-gradient-to-r from-stone-200 to-stone-100`}>{children}</body>
    </html>
  );
}
